insert into floss (brand, color_code, length, thread_count) values ('DMC',310,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',315,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',319,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',500,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',501,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',520,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',522,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',523,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',524,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',644,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',645,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',722,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',823,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',928,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',937,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',939,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3013,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3033,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3047,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3078,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3348,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3363,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3364,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3371,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3768,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3816,'8.7',6);
insert into floss (brand, color_code, length, thread_count) values ('DMC',3823,'8.7',6);

insert into floss_pattern (name, size, height, width) values ('Darth Vader Death Star',14,'37','23');
insert into floss_pattern (name, size, height, width) values ('Darth Vader Death Star',16,'32.2','20');
insert into floss_pattern (name, size, height, width) values ('Darth Vader Death Star',18,'28.6','17.8');
insert into floss_pattern (name, size, height, width) values ('Darth Vader Death Star',20,'25.3','16');
